var placesLabels = [
"Собор (abbey)",
"Аэропорт (airport_terminal)",
"Аллея (alley)",
"Амфитеатр (amphitheater)",
"Парк аттракционов (amusement_park)",
"Аквариум (aquarium)",
"Акведук (aqueduct)",
"Арка (arch)",
"Галерея (art_gallery)",
"Мастерская (art_studio)",
"Конвейер (assembly_line)",
"Чердак (attic)",
"Аудитория (auditorium)",
"Многоквартирный дом (apartment_building/outdoor)",
"badlands",
"Зал (ballroom)",
"Бамбуковый лес (bamboo_forest)",
"Торжественный зал (banquet_hall)",
"Бар (bar)",
"Поле для бейсбола (baseball_field)",
"Подвал (basement)",
"Базилика (basilica)",
"Болото (bayou)",
"Салон красоты (beauty_salon)",
"Спальня (bedroom)",
"boardwalk",
"Палуба (boat_deck)",
"Книжный магазин (bookstore)",
"Ботанический сад (botanical_garden)",
"Боулинг (bowling_alley)",
"Боксёрский ринг (boxing_ring)",
"Мост (bridge)",
"building_facade",
"bus_interior",
"butchers_shop",
"butte",
"bakery/shop",
"Столовая (cafeteria)",
"campsite",
"Кондитерская (candy_store)",
"Каньон (canyon)",
"Замок (castle)",
"cemetery",
"chalet",
"Учебная комната (classroom)",
"Чулан (closet)",
"Магазин одежды (clothing_store)",
"Побережье (coast)",
"cockpit",
"coffee_shop",
"conference_center",
"conference_room",
"Стройка (construction_site)",
"Кукуразное поле (corn_field)",
"Коридор (corridor)",
"cottage_garden",
"Административное здание (courthouse)",
"Двор (courtyard)",
"Ручей (creek)",
"crevasse",
"Пешеходный переход (crosswalk)",
"Церковь (cathedral/outdoor)",
"Церковь (church/outdoor)",
"Плотина (dam)",
"Кухня (dining_room)",
"Пристань (dock)",
"Спальная комната (dorm_room)",
"driveway",
"Пустыня (desert/sand)",
"Пустыня (desert/vegetation)",
"Обеденный стол (dinette/home)",
"doorway/outdoor",
"engine_room",
"Раскопки (excavation)",
"fairway",
"Пожарный выход (fire_escape)",
"Пожарная станция (fire_station)",
"food_court",
"Лесная тропа (forest_path)",
"Лесная дорога (forest_road)",
"Сад (formal_garden)",
"Фонтан (fountain)",
"Поле (field/cultivated)",
"Поле (field/wild)",
"galley",
"Игровая комната (game_room)",
"Свалка (garbage_dump)",
"Заправка (gas_station)",
"Сувенирная лавка (gift_shop)",
"Поле для гольфа (golf_course)",
"Гавань (harbor)",
"Сад (herb_garden)",
"Шоссе (highway)",
"home_office",
"Больница (hospital)",
"Палата (hospital_room)",
"Горячий источник (hot_spring)",
"Номер в отеле (hotel_room)",
"Отель (hotel/outdoor)",
"ice_cream_parlor",
"Айсберг (iceberg)",
"Иглу (igloo)",
"Островок (islet)",
"Каток (ice_skating_rink/outdoor)",
"Гостиница (inn/outdoor)",
"Тюремная камера (jail_cell)",
"kasbah",
"Детский сад (kindergarden_classroom)",
"Кухня (kitchen)",
"Кухня (kitchenette)",
"Стиральная машина (laundromat)",
"Маяк (lighthouse)",
"Гостиная комната (living_room)",
"Холл (lobby)",
"Шкафчик (locker_room)",
"Особняк (mansion)",
"Болото (marsh)",
"Зал боевых искусств (martial_arts_gym)",
"Склеп (mausoleum)",
"medina",
"Мотель (motel)",
"Гора (mountain)",
"Заснеженные горы (mountain_snowy)",
"Студия (music_studio)",
"Рынок (market/outdoor)",
"Монастырь (monastery/outdoor)",
"Музей (museum/indoor)",
"Детская комната (nursery)",
"Океан (ocean)",
"Офис (office)",
"Оффисное здание (office_building)",
"Фруктовый сад (orchard)",
"pagoda",
"Дворец (palace)",
"Кладовка (pantry)",
"Парковка (parking_lot)",
"Кабинет (parlor)",
"Пастбище (pasture)",
"Двор (patio)",
"Павильон (pavilion)",
"Телефонная будка (phone_booth)",
"Парк (picnic_area)",
"Игровая площадка (playground)",
"Площадь (plaza)",
"Пруд (pond)",
"Кафедра (pulpit)",
"Ипподром (racecourse)",
"Плот (raft)",
"Рельсы (railroad_track)",
"Тропический лес (rainforest)",
"reception",
"Жилой район (residential_neighborhood)",
"Ресторан (restaurant)",
"Кухня ресторана (restaurant_kitchen)",
"Зал ресторана (restaurant_patio)",
"Рисовое поле (rice_paddy)",
"Река (river)",
"Горная арка (rock_arch)",
"Верёвочная переправа (rope_bridge)",
"Руины (ruin)",
"Взлётно-посадочная полоса (runway)",
"Песчаная отмель (sandbar)",
"Школа (schoolhouse)",
"Утёс (sea_cliff)",
"Сарай (shed)",
"Обувной магазин (shoe_shop)",
"Витрина магазина (shopfront)",
"Душ (shower)",
"Горнолыжный курорт (ski_resort)",
"Горнолыжный спуск (ski_slope)",
"Небо (sky)",
"Небоскрёб (skyscraper)",
"Трущобы (slum)",
"Заснеженное поле (snowfield)",
"Лестница (staircase)",
"Магазин (supermarket)",
"Топь (swamp)",
"Бейсбольный стадион (stadium/baseball)",
"Футбольный стадион (stadium/football)",
"Сцена (stage/indoor)",
"Платформа метро (subway_station/platform)",
"Бассейн (swimming_pool/outdoor)",
"Телевизионная студия (television_studio)",
"Сад (topiary_garden)",
"Башня (tower)",
"Железная дорога (train_railway)",
"Плантация (tree_farm)",
"Траншея (trench)",
"Храм (temple/east_asia)",
"Храм (temple/south_asia)",
"Дорога (track/outdoor)",
"Платформа (train_station/platform)",
"Коралловый риф (underwater/coral_reef)",
"Долина (valley)",
"Огород (vegetable_garden)",
"Веранда (veranda)",
"Виадук (viaduct)",
"Вулкан (volcano)",
"Комната ожидания (waiting_room)",
"Водонапорная башня (water_tower)",
"Водопой (watering_hole)",
"Пшеничное поле (wheat_field)",
"Ветряная мельница (wind_farm)",
"Мельница (windmill)",
"Лужайка (yard)"];
